name: Release Publisher

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      publish:
        required: false
        default: true
        type: boolean

permissions:
  contents: read

jobs:
  publish_release:
    permissions:
      contents: write
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - name: Set version env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: release-drafter/release-drafter@v6
        with:
          config-name: draft-template.yml
          disable-autolabeler: true
          name: ${{ env.RELEASE_VERSION }} 😍️
          tag: ${{ env.RELEASE_VERSION }}
          version: ${{ env.RELEASE_VERSION }}
          publish: ${{ github.event.inputs.publish == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}