name: Tag Publisher

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: the tag-ref to release e.g. 'v1.0.0'
    

permissions:
  contents: write
  pull-requests: read

jobs:
  build:
    uses: ./.github/workflows/draft-pub.yml
    # The 'publish' input parameter is used to control whether the release should be published automatically.
    # Uncomment and set to 'false' if you want to prevent the release from being published immediately.
    with:
      version: ${{ inputs.tag }}
      #publish: false
